### ISSUE TITLE
Everything should update

### ISSUE THREAD

**Issue by joereynolds** [joereynolds/metronome#1]
Not just the the note type but also note duration and tempo.

**Comment by joereynolds** [comment]
- [x] Tempo
- [x] Amount of notes
- [x] Type of note

**Comment by ducmtran** [comment]
Hi, I found out about your repo on the hacktoberfest reddit post on r/programming. I am new to programming (in college right now) and github's issues/PR. Your repo seems like a good place for me to start. Do you mind if I try to work on your issues, maybe starting with this? Sorry in advance if this is not the place to say this.

**Comment by joereynolds** [comment]
By all means go for it :D 
If you need any help just ask
