### ISSUE TITLE
Update CSS

### ISSUE THREAD

**Issue by CodedChai** [joereynolds/metronome#12]
I was thinking about using Bootstrap or maybe Material to update the look of everything and make it look more modern. I wasn't sure what your thoughts were on that. Any input you may have on this would be great. I would assume you would like to keep the current color scheme as well. This would also help update the look of the sliders.

**Comment by joereynolds** [comment]
The CSS needs tidying but I don't want to bring in any frameworks for this, I want to keep it bloat free.

I'll take a look at material to see if we can use that without it instantly looking like an android app

**Comment by joereynolds** [comment]
It would be good to include something to style the slider since that's a bit more heavyweight. Everything else I think can be done sans-framework quite easily I think

**Comment by joereynolds** [comment]
I'm closing this for now, the CSS will be constantly updating and there's already an issue to style the slider. Thanks for the input! :D
