### ISSUE TITLE
Tap to change BPM

### ISSUE THREAD

**Issue by Dreistein** [joereynolds/metronome#13]
Often enough, i find myself in the situation, to not know the exact tempo i have in my mind. It would be nice to add a sort of tap counter that changes the tempo according to tap speed/ tap intervals.
This is also nice when tapping along a piece of music, to get the exact tempo.

For an example look at this page: http://www.all8.com/tools/bpm.htm

**Comment by WillBrindle** [comment]
Happy to look at getting this is accepted.

**Comment by joereynolds** [comment]
By all means go for it :D
