### ISSUE TITLE
Options close button

### ISSUE THREAD

**Issue by mark-gerarts** [joereynolds/metronome#17]
Currently, the options box can only be toggled by pressing 'Options'. I've added a close button on my fork. If you're interested I can submit it as a PR? :)

Screenshot: 
![options-close-button](https://user-images.githubusercontent.com/11940560/31049108-7ccc20bc-a62c-11e7-8f2c-741d24a293b4.png)

**Comment by joereynolds** [comment]
Definitely interested, go ahead with pr!

**Comment by joereynolds** [comment]
https://github.com/joereynolds/metronome/commit/f70a77622f3ff5ec0ecc53062218795a7106283a
