### ISSUE TITLE
Bpm value on page refresh

### ISSUE THREAD

**Issue by mark-gerarts** [joereynolds/metronome#20]
When you change the bpm value, and refresh the page afterwards, the UI will still show 120bpm as the value unitl you press play (see screenshot). 

What would be the desired effect on refreshing? We could either reset the bpm to 120, or remember the value and fix the display bug.

 If you let me know what you prefer, I could go ahead and implement it :)

![bpm-value-on-refresh](https://user-images.githubusercontent.com/11940560/31053814-c944b372-a6a5-11e7-9ffb-8f082136cc52.png)

**Comment by joereynolds** [comment]
What browser are you using? That doesn't seem to happen on Chrome.

Either way, we should reset to 120bpm, I can't see why that's happening though :S  
Must be browser-specific :(

**Comment by mark-gerarts** [comment]
It's browser-related indeed. I'm using FF 55.0.3, which has this issue. Chrome is fine. I'll take a look at it!
