### ISSUE TITLE
Play/Pause vs. Start/Stop

### ISSUE THREAD

**Issue by TJScalzo** [joereynolds/metronome#30]
The button that toggles the metronome switches between "Play" and "Pause" when it's clicked. However, when you press play after pausing it it doesn't resume where it was, it restarts from 1. Because of this, I argue that "Start" and "Stop" are more accurate labels for the button. If you'd like, this could become another option; starting and stopping the metronome or pausing and resuming.

TL;DR: Start and stop are more accurate words for the toggle button. If you'd like, I could work on a feature that lets the user pick the toggle button's behavior.

**Comment by joereynolds** [comment]
Hey @TJScalzo, you're right. Just a text change would suffice, there's no need for this to be an option.

Thanks!
