### ISSUE TITLE
Is there an open source license?

### ISSUE THREAD

**Issue by jophy** [joereynolds/metronome#34]
It's a nice metronome I have ever seen before.

Could I use it on my personal project?

I found no open source license here

**Comment by joereynolds** [comment]
Hey @jophy,

I will add one in soon. In the meantime, feel free to use it for anything you want :D

**Comment by joereynolds** [comment]
Hey @jophy 

Sorry about the mega late response, I've added a LICENSE.

https://github.com/joereynolds/metronome/commit/6ca6a67bde7003bc223236187e3fafcab6cc85be

**Comment by jophy** [comment]
It's happy to see MIT license here.

You are so nice. Thank you.
