### ISSUE TITLE
More types of wave

### ISSUE THREAD

**Issue by joereynolds** [joereynolds/metronome#8]
Square, triangle etc...
Currently it's sine only.
Look into the webaudio API 
https://developer.mozilla.org/en-US/docs/Web/API/OscillatorNode/type

**Comment by CodedChai** [comment]
I'm willing to tackle this. How would you want it to work? Should there be a button on the screen that changes the wave type or a drop down or what do you prefer?

**Comment by joereynolds** [comment]
It should be under the options menu as a drop down menu ideally. 
If you can think of a nicer way, I'm up for suggestions :D

**Comment by CodedChai** [comment]
I'll plan on implementing it like that initially! I might not be able to completely get around to it until Monday but I'll definitely get it done! Seems like a fun project.

**Comment by joereynolds** [comment]
No worries, any issues just ask

**Comment by CodedChai** [comment]
I ended up getting to it just now. Sent a pull request.

**Comment by joereynolds** [comment]
https://github.com/joereynolds/metronome/commit/b7477a494c4056cbc017729abb6cbacd3c468c2f
